name: ts

on:
  push:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # wiki
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - run: sudo apt-get install -y --no-install-recommends imagemagick
      - run: 'convert logo: -resize 256x256 output.png'
      - name: Run upload-artifact-wiki
        id: upload-artifact-wiki
        uses: ./
        with:
          path: output.png
      - uses: int128/comment-action@aeac1a068baa6d17e9673b817d27a310185aa95b # v1.58.0
        with:
          update-if-exists: replace
          post: |
            ## :sparkles: Uploaded artifact
            <img width="128" src="${{ steps.upload-artifact-wiki.outputs.url }}/output.png">

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm run check
      - uses: int128/update-generated-files-action@a5f0fd965599f7216e8a6bac705929e97c17745d # v2.92.0
